export { Home } from './Home'
export { FullPost } from './FullPost'
export { FullTags } from './FullTags'
export { AddPost } from './AddPost'
export { Registration } from './Registration'
export { Login } from './Login'
